### ISSUE TITLE
Dusty smell in rear bedroom

### ISSUE THREAD

**Issue by frabcus** [frabcus/house#118]
Kind of similar to described here http://ths.gardenweb.com/forums/load/disaster/msg1010472622080.html?3

Possibly replaster corner where cupboard was, certainly seal the floor and skirting board properly there.

**Comment by jared3dmc** [comment]
Shouldn't redoing the floor be a separate ticket?

**Comment by frabcus** [comment]
Maybe try:

http://allertongeneralbuilders.co.uk/
http://www.prnsbuildingservices.co.uk/private-clients/

**Comment by frabcus** [comment]
@jared3dmc - in particular the skirting boards need fixing. I'm not sure if the plasterer or flooring people will do this...

**Comment by frabcus** [comment]
Try:
http://callaghanplastering.co.uk/
http://empire-plastering.co.uk/plastering/2674704

**Comment by frabcus** [comment]
Seems to have gone with time.

Opened https://github.com/frabcus/house/issues/135 instead
