### ISSUE TITLE
kitchen tap drips

### ISSUE THREAD

**Issue by drj11** [frabcus/house#127]
About 25l per day

**Comment by Unihedro** [comment]
Contact a technician. I was just searching for ways to solve tap drips, and by the time I found this issue I knew there was no way to avoid spending money on hiring people for that.

**Comment by frabcus** [comment]
Yes, that's what I did in the end!

Well, I tried to fix it myself but got stuck even getting the mains water fully turned off (it was slightly dripping), and the newer washer to get was non-obvious.

Turned out it needed an entire new tap, which is apparently normal nowadays when they go wrong...
