### ISSUE TITLE
Door hung wrong way (living room)

### ISSUE THREAD

**Issue by frabcus** [frabcus/house#58]
It probably would be better hung the other way round so that it opens the other way.

**Comment by RossMNelson** [comment]
@frabcus is @akuckartz your wife?  My wife asks me the same thing all the time.

**Comment by frabcus** [comment]
@RossMNelson not that I can remember ;)

**Comment by wedidit** [comment]
Good job!

**Comment by UFUKGOCMEN** [comment]
all right

**Comment by janjakjur** [comment]
Come on. Fix it already :tired_face:

**Comment by fer-rum** [comment]
May I instead suggest to re-factor the one-directional hinged door into a bi-directionally hinged one?
Alternatively, you could implement a sliding door or a maybe a curtain?

**Comment by OvermindDL1** [comment]
Bit-directional doors have an issue with not being able to seal the edges around though, and issue if an outer door or bathroom or bedroom or so, not an issue with closets or such variants.

**Comment by vyruz1986** [comment]
As a work-around for not having to reposition the light switch, you could go for a PIR-sensor automatic light switch. Whenever you enter the room the light would turn on automatically.

**Comment by surajreddy** [comment]
We should think simple - just get rid of the door - it only gets in the way anyway.

**Comment by gerv** [comment]
Perhaps a door which hinges at the top and opens vertically? This gives light switch access to either side. Flexible.

(This is an engineer's solution, not a UX person's solution :-)

**Comment by clinch** [comment]
Bead curtains should at least be considered. They allow for good airflow, semi-privacy, and the light switch can be located on either side of the door way.

Plus, it'll give your house that 60's hippie "je ne sais quoi".

**Comment by danielchristiancazares** [comment]
Please consider double-hinged door for backwards compatibility. Changing functionality will break my current workflow.

**Comment by Kubo2** [comment]
@frabcus Still haven't fixed this? It's been about four years since then :D

**Comment by johnhunt** [comment]
@eyesparky this.

**Comment by matthew-dean** [comment]
+1

**Comment by rask** [comment]
@danielchristiancazares and he would avoid having to bump the major version of his house that way. Good point. :D

**Comment by benrj** [comment]
Came here because I have this exact problem in my house.  Sadly, it's a house I designed and (helped) build.  

The painful irony of it all is that the other night I stubbed/broke my toe on it, as it was awkwardly and improperly open into the bathroom.  Here are the steps:

- remove door slabs by tapping hinge pins out
- cut caulk around existing door trim
- carefully pry trim off both sides of the door and set aside
- cut and remove nails attaching door jambs to framing
- carefully remove door jambs
- re-hang door (see YouTube)
- re-attach trim
- caulk, paint, and never speak of it again

**Comment by jameshnsears** [comment]
@frabcus - forget your worries about light switches, instead why not go for a a [painted bead curtain](https://www.pinterest.co.uk/bamboocurtainvn/bamboo-painted-beaded-curtain/)?

**Comment by Hammster** [comment]
@frabcus removing the door would improve the airflow.

**Comment by s41m1r** [comment]
@frabcus If everything else has been working so far, I would propose the following change **Issue** --> **Feature**.

**Comment by rattikarl** [comment]
Remove Internet

**Comment by nallown** [comment]
@frabcus this issue is giving me merge conflicts with the door handle installation, can you please fix this issue asap?

**Comment by danielchristiancazares** [comment]
I’ve transitioned into an Ops role since my original post. Solution is to keep door open at all times. No security issues that I can think of since if they’ve managed to penetrate the front door of your house, they can get anywhere else.

**Comment by rask** [comment]
@danielchristiancazares just remember to add an exception for bathroom doors for a better user experience.

**Comment by frabcus** [comment]
Won't fix

**Comment by matthew-dean** [comment]
This is the best 6-year journey on Github I've ever taken.

**Comment by mueller-ma** [comment]
The onyl thing that makes this issue different to all other "Won't fix" six years after opening is 

> frabcus locked and limited conversation to collaborators
