### ISSUE TITLE
Insulate walls

### ISSUE THREAD

**Issue by frabcus** [frabcus/house#65]
A recommends Parity Projects (http://www.parityprojects.com/) for getting general insulation type analysis. See if they work in Liverpool.

**Comment by mitselek** [comment]
Yes. Just make sure you support the frame - foam tends to bend it and you'll have trouble closing the door later :)

**Comment by mitselek** [comment]
wonder how such simple task could take four years...

**Comment by ProIcons** [comment]
5

**Comment by frabcus** [comment]
Won't fix for now.
